# Session 6

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a.shape

(3, 4)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[ 1:  , 1:3 ]  # last is exclusive

array([[ 6,  7],
       [10, 11]])

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[ 0:2,1:3]      # rows 1 :3 ,  columns    
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
# print(a[0, 1])
print(b)
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(b)
# print(a[0, 1]) 

[[ 7  8]
 [11 12]]
[[77  8]
 [11 12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a.shape

(4, 3)

In [ ]:
a[ 1:3 ]

array([[4, 5, 6],
       [7, 8, 9]])

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
# #                     # this returns a numpy array of Booleans of the same
# #                     # shape as a, where each slot of bool_idx tells
# #                     # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
# print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[a < 5] 

array([1, 2, 3, 4])

In [ ]:
task 

1- create array 2d   shape 3 , 4 

2- print > 5 

3-  print row 2 col 3 

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Int16 can only store values up to 2^16 =  32,767  

Int32 can store values up to 2^31  =  2,147,483,647  

Int64 can store values up to 2^63   = 9,223,372,036,854,775,807    

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
# Elementwise sum; both produce the array
# print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Task 

1- create function takes two arrays  size of array (3,3)

2- print multiply two arrays

3- print subtract 2 arrays

4- return sub array size 2,2 from result of mutlipy


task 


create array  4*3 

make multiply * 3




In [ ]:
import numpy as np

In [ ]:
x = np.array([[1 ,2],[3 , 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
# x = np.array([[1,2],[3,4]])
# y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])   # 9 * 11 + 10*12  = 99 + 120 = 219

print (v)
print(w)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

[ 9 10]
[11 12]
219
219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2,3],[6,3,8],[8,3,4]])
print(x)
print(np.sum(x))        # Compute sum of all elements; prints 
print(np.sum(x, axis=0))  # Compute sum of each column; prints 
# print(np.sum(x, axis=1))  # Compute sum of each row; prints 

[[1 2 3]
 [6 3 8]
 [8 3 4]]
38
[15  8 15]


In [ ]:
x=np.arange(1,7).reshape(2,3)
print(x)
np.sum(x,axis = 0)

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n",
        x.T
        )  # T is capital   Transpose

[[1 2 3]
 [4 5 6]]
transpose
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
v = np.array([[1,2,3]])
print( v )
print( "transpose\n", v.T   )

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


 2 3 6 1 2 5

 n = 6

 sum = 19 
 
 mean = sum / n    >> Average
 

In [ ]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(x, axis = 0)  # mean over columns 

array([2.5, 3.5, 4.5])

In [ ]:
np.median(x, axis = 0)

array([2.5, 3.5, 4.5])

In [ ]:
np.min(x,axis=0)

array([1, 2, 3])

In [ ]:
np.max(x,axis=0)

array([4, 5, 6])

## Exercise

calculate mean of array with

[[ 0 1 2 3 4]

[ 5 6 7 8 9]

[10 11 12 13 14]

[15 16 17 18 19]]

1- print  mean total array

2- print mean every columns 

3- print median every columns



In [ ]:
x = np.array([
            [0,1,2,3,4],
            [5,6,7,8,9],
            [10,11,12,13,14],
            [15,16,17,18,19]
            ])
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

1- 

In [ ]:
print(np.mean(x))

9.5


2-

In [ ]:
print(np.mean(x,axis = 0))

[ 7.5  8.5  9.5 10.5 11.5]


3- 


In [ ]:
print(np.median(x,axis = 0))

[ 7.5  8.5  9.5 10.5 11.5]


## Reference & Credits:

The tutorial above is a combination of the code/instructions created by 

Eng / Mahmoud Khorshed 